site_name: Casa dei Flanders
site_url: https://paginablanda.org
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight 
    - search.share

plugins:
 - search
 - tags

nav:
   - Home: index.md
   - Heylà: 
      - Ma quello è Ned?: index.md
   - Chi sono: 
      - Info generali: Ned/about.md
      - Origiineine: Ned/Infanziainainaina.md

